chore: handle env urls dynamically
itzMaffi/CW-thesis-project pull request #84
Opened 2023-12-02 18:00 UTC by dinarabs

- added handling env urls dynamically 👯 
- changed some styling of userProfile per @muzixiaowuwuyi suggestion 🎨 
- @dayt47  already added FRONTEND_URL & BACKEND_URL to railway env configs ⛓️

2023-12-02 18:31 UTC, dayt47 requested changes

2023-12-02 18:31 UTC, dayt47 commented on Agenda-client/src/components/LoginPage/LogIn.tsx
on client side we cannot use process.env, but `import.meta.env.VITE_BACKEND_URL`

2023-12-02 18:31 UTC, dayt47 commented on Agenda-client/Dockerfile
i think there is no need to put the environment variable here, i added VITE_BACKEND_URL directly via website..

2023-12-02 18:31 UTC, dayt47 commented on Agenda-client/src/components/LoginPage/LogIn.tsx
i think VITE_BACKEND_URL should also work..

2023-12-04 09:28 UTC, dinarabs commented on Agenda-client/src/components/LoginPage/LogIn.tsx
true, i forgot about `import.meta.env`, i've researched and we need to use import, not just VITE_BACKEND_URL because how Vite works. I'll change to `import.meta.env`.

2023-12-04 16:26 UTC, dayt47 approved these changes

2023-12-04 16:26 UTC, merged